"""Create initial tables

Revision ID: 5c29706b2dfb
Revises: 3c94b36dde52
Create Date: 2024-09-18 06:54:54.088830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c29706b2dfb'
down_revision: Union[str, None] = '3c94b36dde52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venues')
    op.add_column('concerts', sa.Column('name', sa.String(), nullable=False))
    op.drop_constraint(None, 'concerts', type_='foreignkey')
    op.drop_column('concerts', 'venue_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concerts', sa.Column('venue_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'concerts', 'venues', ['venue_id'], ['id'])
    op.drop_column('concerts', 'name')
    op.create_table('venues',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('city', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
